# Generated by Django 4.1.5 on 2023-01-27 21:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_likes_post_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='max 1000 characters', max_length=1000, null=True),
        ),
    ]
