# Generated by Django 4.1.5 on 2023-02-02 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='replay',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_post',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='blog_posts_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
