# Generated by Django 4.1.5 on 2023-02-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_likes_remove_post_replay_post_likes_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
    ]
